### ISSUE TITLE
Using multiple queues on a single connection: is this possible?

### ISSUE THREAD

**Issue by ArondeParon** [brefphp/laravel-bridge#119]
# What is the current issue?

With the setup below, my jobs seem to be dispatched to the correct SQS queue, but after this it seems like `deleteMessage` is called (which I don't think should happen if I dispatch a job that does not fail?). Further more, this call to `deleteMessage` seems cause _another_ error because it is trying to delete the message on the default (`SQS_QUEUE`) queue instead of the queue that the message has been pushed to.

In short: am I doing this wrong? What is the best way to configure multiple queues with Bref and Laravel?

# What I want to achieve

- `SQS_QUEUE` should be my "default" queue
- `SQS_QUEUE_HIGH` should be my high priority queue for high priority jobs
- `SQS_QUEUE_LOW` for jobs that can take a bit longer (background jobs)

I then map these queue urls to config variables in Laravel.

From my code, I then reference this queues as follows: `FoobarJob::dispatch()->onQueue(config('queue.queues.high'))`

# What I already did

*serverless.yml*:
```yml

provider:
.........................
    environment:
        QUEUE_CONNECTION: sqs
        SQS_QUEUE: ${construct:jobs.queueUrl}
        SQS_QUEUE_HIGH: ${construct:jobs-high.queueUrl}
        SQS_QUEUE_LOW: ${construct:jobs-low.queueUrl}
.....................
    jobs:
        type: queue
        maxConcurrency: 25
        worker:
            handler: Bref\LaravelBridge\Queue\QueueHandler
            runtime: php-82
            timeout: 300

    jobs-high:
        type: queue
        maxConcurrency: 50
        worker:
            handler: Bref\LaravelBridge\Queue\QueueHandler
            runtime: php-82
            timeout: 300

    jobs-low:
        type: queue
        maxConcurrency: 25
        worker:
            handler: Bref\LaravelBridge\Queue\QueueHandler
            runtime: php-82
            timeout: 300
```
