### ISSUE TITLE
Laravel app is not creating XSRF-TOKEN cookie

### ISSUE THREAD

**Issue by mhetreramesh** [brefphp/laravel-bridge#32]
As per laravel [docs](https://laravel.com/docs/8.x/csrf#csrf-x-xsrf-token), every application should create encrypted `XSRF-TOKEN` cookie. I also have this cookie dev environment but not on lambda function.

I've tried adding custom header for lambda function ins serverless file, like:

```
functions:
  # This function runs the my website/API
  web:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
      - ${bref:extra.gd-php-74}
    events:
      - httpApi: '*'
        cors:
          origin: '*'
          headers:
            - X-XSRF-TOKEN
```

![image](https://user-images.githubusercontent.com/3095445/104559987-804a0980-5645-11eb-9c2a-fa02a8b73719.png)

I need this to use on my frontend application to use it in `axios`.

Does someone has any idea if I'm missing something?

**Comment by aristidesneto-bnw** [comment]
Did you manage to solve it?

I managed to solve it by going straight to the CloudFront panel and adding the X-CSRF-TOKEN header to the Policy (custom policies -> cache key settings).

But using the `serverless.yml` file I had no success following as described in the documentation https://github.com/getlift/lift/blob/master/docs/server-side-website.md#forwarded-headers.

I would not like to add the header manually through CloudFront, but through the serverless.yml configuration file

**Comment by evrend** [comment]
@aristidesneto-bnw Thank you very much for lift doc's link. After 3-4 hours, finally, I solved the "X-CSRF-TOKEN" header problem.  I added "X-CSRF-TOKEN" token to `serverless.yml` as in the lift documents. And it works perfectly.
```
constructs:
    website:
        type: server-side-website
        domain: ***********
        certificate: arn:aws:************
        forwardedHeaders:
            - X-XSRF-TOKEN
            - Origin
            - Accept
            ....
```

Result:

![image](https://user-images.githubusercontent.com/5174632/167269313-2f4efefa-a75b-47a0-8774-d90e771c2338.png)
