### ISSUE TITLE
How can I setup multiple queues?

### ISSUE THREAD

**Issue by hanachan1026** [brefphp/laravel-bridge#62]
When I setup single queue, it works like a charm. But if I want to have multiple queues, since we can only specify one queue url in `SQS_QUEUE` I don't know how to setup.

The reason why I want multiple queues in 1 application is that I want to know if a specific job is still processing. To do that I separate queues for each jobs and long polling the status of queue.

**Comment by mnapoli** [comment]
I think you would have to create a new queue connection in `config/queue.php` (per Laravel's documentation).

And then:

- duplicate the `worker` function
- duplicate the `worker.php` file and change the queue connection and queue name used in there (I mean these lines: https://github.com/brefphp/laravel-bridge/blob/36111f777e78759c2f20e9555dea2cd92e606916/worker.php#L19-L20)

**Comment by aristidesneto-bnw** [comment]
@mnapoli Could you tell why this implementation does not work?

I'm dynamically getting the queue name through the event variable. It doesn't show any error, but also the message is not sent to the queue.

```
return function (array $event, Context $context) {

    /** @var Application $app */
    $app = require __DIR__ . '/bootstrap/app.php';

    $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
    $kernel->bootstrap();

    $message = $event['Records'][0];

    $queueName = explode(':', $message['eventSourceARN'])[5];

    $queueUrl = getenv('SQS_PREFIX') . $queueName;

    Log::info("Message '{$message['messageId']}' sent to '{$queueUrl}' ");
    
    return $app->makeWith(LaravelSqsHandler::class, [
        'connection' => 'sqs',
        'queue' => $queueUrl,
    ]);
};
```

Would you help me?
Thanks

**Comment by alexw23** [comment]
Did you figure this out?

I haven't tested this but you should be able to put an [environment variable per handler](https://www.serverless.com/framework/docs/providers/aws/guide/functions/#:~:text=Access%20within%20VPC-,Environment%20Variables,-You%20can%20add).

Will report back.

```yml
constructs:
    primary-queue:
        type: queue
        worker:
            handler: Bref\LaravelBridge\Queue\QueueHandler
            runtime: php-81
            timeout: 60 # seconds
            environment:
                 SQS_QUEUE: primary
     secondary-queue:
        type: queue
        worker:
            handler: Bref\LaravelBridge\Queue\QueueHandler
            runtime: php-81
            timeout: 60 # seconds
            environment:
                 SQS_QUEUE: secondary
```
