### ISSUE TITLE
How can I set iamRolePolicies for function declared in constructs?

### ISSUE THREAD

**Issue by hanachan1026** [brefphp/laravel-bridge#63]
I'm using bref-php & serverless-lift & laravel-bridge library for SQS + Lambda functions, and I see that `iamRoleStatement` is not attached to functions declared in constructs.

```
constructs:
  sqs_function1:
    type: queue
    worker:
      handler: worker.php
      timeout: 600
      layers:
        - ${bref:layer.php-80}
      vpc:
        securityGroupIds:
          - sg-xxxx
        subnetIds:
          - subnet-xxxx
          - subnet-xxxx
      iamRoleStatements:
        - Effect: "Allow"
          Action:
            - "s3:*"
            - "s3-object-lambda:*"
          Resource: "*"
```

I tried like above but I couldn't make it & I couldn't find the documentation about this.
